# Generated by Django 4.2.7 on 2024-01-10 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_alter_property_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="location",
            new_name="area",
        ),
    ]
